## Clock signal (W5 pini 100MHz osilatör)
set_property PACKAGE_PIN W5 [get_ports sys_clock]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports sys_clock]

## Reset button (Ortadaki Tuþ - U18)
# Block Design'daki reset portunun adý neyse (reset, rst, reset_rtl) buradaki parantez içine onu yaz!
set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

## LEDs (Basys 3 üzerindeki 16 LED)
set_property PACKAGE_PIN U16 [get_ports {leds_16bits_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[0]}]
set_property PACKAGE_PIN E19 [get_ports {leds_16bits_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[1]}]
set_property PACKAGE_PIN U19 [get_ports {leds_16bits_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[2]}]
set_property PACKAGE_PIN V19 [get_ports {leds_16bits_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[3]}]
set_property PACKAGE_PIN W18 [get_ports {leds_16bits_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[4]}]
set_property PACKAGE_PIN U15 [get_ports {leds_16bits_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[5]}]
set_property PACKAGE_PIN U14 [get_ports {leds_16bits_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[6]}]
set_property PACKAGE_PIN V14 [get_ports {leds_16bits_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[7]}]
set_property PACKAGE_PIN V13 [get_ports {leds_16bits_tri_o[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[8]}]
set_property PACKAGE_PIN V3 [get_ports {leds_16bits_tri_o[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[9]}]
set_property PACKAGE_PIN W3 [get_ports {leds_16bits_tri_o[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[10]}]
set_property PACKAGE_PIN U3 [get_ports {leds_16bits_tri_o[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[11]}]
set_property PACKAGE_PIN P3 [get_ports {leds_16bits_tri_o[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[12]}]
set_property PACKAGE_PIN N3 [get_ports {leds_16bits_tri_o[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[13]}]
set_property PACKAGE_PIN P1 [get_ports {leds_16bits_tri_o[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[14]}]
set_property PACKAGE_PIN L1 [get_ports {leds_16bits_tri_o[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_16bits_tri_o[15]}]